version: '3.4'
services:
    client:
        image: nginx
        volumes:
            - ./bin/www:/usr/share/nginx/html
        ports:
            - '${PORT:-80}:80'
        restart: unless-stopped
    server:
        image: node:13
        network_mode: host
        command: bash -c "yarn --production && node server.js"
        volumes:
            - ./bin:/app
            - ./package.json:/app/package.json
            - ./yarn.lock:/app/yarn.lock
            - yarn-cache:/root/.yarn-cache
        working_dir: /app
        restart: unless-stopped

volumes:
    yarn-cache:
